const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(root, f), 'utf8');
const pkg = JSON.parse(read('package.json'));
const index = read('index.html');
const sw = read('sw.js');
const ui = read('ui.js');
const core = read('ui-modules/ui-core.part.js');
const modules = fs.readdirSync(path.join(root, 'ui-modules')).filter(x => x.endsWith('.part.js'));
assert.equal(modules.length, 6, 'six UI modules expected');
assert(index.includes(`application-version" content="${pkg.version}"`), 'HTML release must match package version');
assert(index.includes('viewport-fit=cover'), 'safe-area viewport must remain enabled');
assert(index.indexOf('error-handler.js') < index.indexOf('storage.js'), 'error handler must boot first');
assert(sw.includes(`CACHE_NAME='dakshinamurthy-v${pkg.version}'`), 'SW cache must match package version');
assert(sw.includes('var SHELL=['), 'service-worker shell manifest must remain intact');
assert(sw.includes("'./engine.js'") && sw.includes("'./ui.js'"), 'core assets must remain in SW shell');
assert(sw.includes("'./visual-v33-ui.js'"), 'V33 UI refinement module must remain in offline shell');
assert(!index.match(/<script src="visual-v(?:20|21|22|23|24|25|26|27|28|32|33)\.js"><\/script>/), 'legacy visual runtime must not boot in UI-only branch');
assert(sw.includes(`RELEASE='${pkg.version}'`), 'SW release must match package version');
assert(ui.includes(`production bundle — ${pkg.version}`), 'UI bundle must be stamped with package version');
assert(ui.includes('UI MODULE 1') && ui.includes('UI MODULE 6'), 'all UI modules must be bundled');
assert(!fs.existsSync(path.join(root, 'ui.js.bak')), 'obsolete monolith backup should not ship');
assert(core.includes('function normalizeState(s)'), 'state normalization must be centralized');
assert(core.includes('Saved state failed verification'), 'save verification must be enabled');
assert(core.includes('smStorageEstimate'), 'storage health estimate must be available');
assert(read('error-handler.js').includes('unhandledrejection'), 'runtime rejection boundary must remain installed');
console.log(`SMOKE PASS: ${pkg.version} release, boot order, UI bundle and persistence hardening checks passed.`);
